In [2]:
print('hello')

hello


In [1]:
n=7
fact=1
if n<0:
    print("factorial doesn't exist for negative number")
elif n==0:
    print("factorial of 0 is 1")
else:
    for i in range(1,n+1):
        fact=fact*i
    print("factorial of",n,"is",fact)    
    

factorial of 7 is 5040


In [4]:
a=20
b=25
c=7
if a<b and a>c:
    print('a is largest')
elif b>a and b>c:
    print('b is largest')
else:
    print('c is largest')

a is largest


In [5]:
year=int(input("enter the year"))
if(((year%4==0)and(year%100!=0))or(year%400==0)):
    print("leap year")
else:
    print("not a leap year")

enter the year2004
leap year


In [6]:
x=5
y=10
temp=x
x=y
y=temp
print('the value of x after swapping:{}'.format(x))
print('the value of y after swapping:{}'.format(y))

the value of x after swapping:10
the value of y after swapping:5


In [7]:
x=5
y=10
x=x+y
y=x-y
x=x-y
print('the value of x after swapping:{}'.format(x))
print('the value of y after swapping:{}'.format(y))

the value of x after swapping:10
the value of y after swapping:5


In [37]:
import random
print(random.randint(0,9))

5


In [14]:
num1=input('enter first number:')
num2=input('enter second number:')
sum=float(num1)+float(num2)
print('the sum of{0}&{1} is {2}'.format(num1,num2,sum))

enter first number:2
enter second number:9
the sum of2&9 is 11.0


In [16]:
num=8
num_sqrt=num**0.5
print('the sqrt of % 0.3f is 0.3f %num',num_sqrt)

the sqrt of % 0.3f is 0.3f %num 2.8284271247461903


In [41]:
list=[]
print("blank list")
print(list)

In [42]:
list=[10,20,14]
print("List of numbers")
print(list)


List of numbers
[10, 20, 14]


In [2]:
list=["hai","y"]
print(list)

['hai', 'y']


In [16]:
a=20
b=4
print(a&b)
print(a|b)
print(~a)
print(a^b)
print(a<<2)
print(a>>2)



4
20
-21
16
80
5


In [5]:
sum=lambda a:a+15
print(sum(5))    
product=lambda x,y:x*y
product(5,2)

20


10

In [1]:
import numpy 
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np
print(np.__version__)

1.23.5


In [3]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
import numpy as np
arr=np.array([[1,2,3],[4,2,5]])
print("array is of type:",type(arr))
print("no. of dimensions:",arr.ndim)
print("shape of array:",arr.shape)
print("size of array:",arr.size)
print("array stores elements of type:",arr.dtype)

array is of type: <class 'numpy.ndarray'>
no. of dimensions: 2
shape of array: (2, 3)
size of array: 6
array stores elements of type: int32


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [1]:
a=[2,4,6,8,10]
b=a[2:4:1]
print(b)

[6, 8]


In [10]:
a=10
b=1
c=a+b
print(c)

11


In [20]:
a="i am a man"
b=a.split(" ")
b=list(reversed(b))
print(" ".join(b))

man a am i


In [6]:
import numpy as np
x=[[1,2],[3,4]]
np.concatenate([x,x],axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [8]:
x=[1,2]
y=[1,2]
np.append(x,y)

array([1, 2, 1, 2])

In [17]:
import datetime
from datetime import datetime
datetime(year=2015,month=7,day=4)

datetime.datetime(2015, 7, 4, 0, 0)

In [14]:
import pandas as pd
import datetime
pd.Timestamp(datetime.datetime(2012,5,1))

Timestamp('2012-05-01 00:00:00')

In [21]:
from dateutil import parser
date=parser.parse("4 of July,2015")
date

datetime.datetime(2015, 7, 4, 0, 0)

In [22]:
from datetime import datetime
import pandas as pd
import numpy as np
range_date=pd.date_range(start='1/1/2019',end='1/8/2019',freq='Min')
print(range_date)

DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 00:01:00',
               '2019-01-01 00:02:00', '2019-01-01 00:03:00',
               '2019-01-01 00:04:00', '2019-01-01 00:05:00',
               '2019-01-01 00:06:00', '2019-01-01 00:07:00',
               '2019-01-01 00:08:00', '2019-01-01 00:09:00',
               ...
               '2019-01-07 23:51:00', '2019-01-07 23:52:00',
               '2019-01-07 23:53:00', '2019-01-07 23:54:00',
               '2019-01-07 23:55:00', '2019-01-07 23:56:00',
               '2019-01-07 23:57:00', '2019-01-07 23:58:00',
               '2019-01-07 23:59:00', '2019-01-08 00:00:00'],
              dtype='datetime64[ns]', length=10081, freq='T')


In [25]:
df=pd.DataFrame(range_date,columns=['date'])
df['date']=np.random.randint(0,100,size=len(range_date))
print(df.head())

   date
0    48
1    52
2    21
3    46
4    34


In [28]:
string_data=[str(x) for x in range_date]
string_data

['2019-01-01 00:00:00',
 '2019-01-01 00:01:00',
 '2019-01-01 00:02:00',
 '2019-01-01 00:03:00',
 '2019-01-01 00:04:00',
 '2019-01-01 00:05:00',
 '2019-01-01 00:06:00',
 '2019-01-01 00:07:00',
 '2019-01-01 00:08:00',
 '2019-01-01 00:09:00',
 '2019-01-01 00:10:00',
 '2019-01-01 00:11:00',
 '2019-01-01 00:12:00',
 '2019-01-01 00:13:00',
 '2019-01-01 00:14:00',
 '2019-01-01 00:15:00',
 '2019-01-01 00:16:00',
 '2019-01-01 00:17:00',
 '2019-01-01 00:18:00',
 '2019-01-01 00:19:00',
 '2019-01-01 00:20:00',
 '2019-01-01 00:21:00',
 '2019-01-01 00:22:00',
 '2019-01-01 00:23:00',
 '2019-01-01 00:24:00',
 '2019-01-01 00:25:00',
 '2019-01-01 00:26:00',
 '2019-01-01 00:27:00',
 '2019-01-01 00:28:00',
 '2019-01-01 00:29:00',
 '2019-01-01 00:30:00',
 '2019-01-01 00:31:00',
 '2019-01-01 00:32:00',
 '2019-01-01 00:33:00',
 '2019-01-01 00:34:00',
 '2019-01-01 00:35:00',
 '2019-01-01 00:36:00',
 '2019-01-01 00:37:00',
 '2019-01-01 00:38:00',
 '2019-01-01 00:39:00',
 '2019-01-01 00:40:00',
 '2019-01-01 00:

In [29]:
print(string_data[1:11])

['2019-01-01 00:01:00', '2019-01-01 00:02:00', '2019-01-01 00:03:00', '2019-01-01 00:04:00', '2019-01-01 00:05:00', '2019-01-01 00:06:00', '2019-01-01 00:07:00', '2019-01-01 00:08:00', '2019-01-01 00:09:00', '2019-01-01 00:10:00']


In [36]:
import pandas as pd
import numpy as np
rng=np.random.RandomState(42)
df=pd.Series(rng,randint(0,10,4))

NameError: name 'randint' is not defined

In [2]:
a=input("Enter your name:");
b=int(input("enter your age:"));


Enter your name:567
enter your age:456


In [3]:
a=input();
b=input();
c=input();
print("My name is:",a);
print("My age is:",b);
print("My address is:",c);



suba
18
puducheryy
My name is: suba
My age is: 18
My address is: puducheryy


In [4]:
a=10
b=12
c=5
print("The addition is:", (a+b+c));
print("The multiplication is:", (a*b*c));
d=a+b+c;
e=a*b*c;
print("the divided value:",e/d);

The addition is: 27
The multiplication is: 600
the divided value: 22.22222222222222


In [11]:
a=int(input("Enter your mark out of 100:"));
b=(a/100)*10
print("Your cgpa is:",b,"/10");

Enter your mark out of 100:90
Your cgpa is: 9.0 /10


In [13]:
if(False):
    print("yes");
else:
    print("no");

no


In [14]:
print("Win"=="win");

False


In [16]:
meghna=input()
if(meghna=="died" or "no"):
    print("surya meets priya");
else:
    print("surya weds meghna");

no
surya meets priya


In [18]:
mark=int(input("Enter your mark:"));
if(mark>35):
    print("pass");
else:
    print("fail");

Enter your mark:22
fail


In [20]:
a=int(input("Enter a number:"));
if(a%3==0 and a%5==0):
    print("divisible by 3 and 5");
else:
    print("not divisible by 3 and 5");

Enter a number:3
not divisible by 3 and 5


In [22]:
a=int(input("Enter a number:"));
if(a%2==0):
    print("even");
else:
    print("odd");

Enter a number:9
odd


In [26]:
a=int(input("Enter your mark:"));
if(a<35):
    print("poor student");
elif(a>35 and a<70):
    print("average student");
else:
    print("good student")

Enter your mark:60
average student


In [28]:
a=int(input("Enter first no."));
b=int(input("Enter second no."));
print("enter 1 for add,2 for sub,3 for mul,4 for div");
c=int(input());
if(c==1):
    print(a+b);
elif(c==2):
    print(a-b);
elif(c==3):
    print(a*b);
elif(c==4):
    print(a/b);
else:
    print("invalid input");

Enter first no.9
Enter second no.9
enter 1 for add,2 for sub,3 for mul,4 for div
1
18


In [82]:
a=int(input("Enter your score percentage:"));
if(a>70):
    b=input("name:");
    c=input("dept:");
    d=input("location:");
    print("you are eligible");
else:
    print("not eligible");

Enter your score percentage:90
name:suv
dept:cse
location:pughj
you are eligible


In [31]:
a=int(input("salary:"));
b=int(input("age:"));

if(a>=20000 or <=25):
    c=input("enter required loan:");
else:
    print("not elgible for loan");
    

salary:99999
age:99
enter required loan:999999


In [33]:
for i in range(0,11,2):
    print(i);

0
2
4
6
8
10


In [39]:
for i in range(1,11):
    print(i,"* 2 =",i*2);
    

1 * 2 = 2
2 * 2 = 4
3 * 2 = 6
4 * 2 = 8
5 * 2 = 10
6 * 2 = 12
7 * 2 = 14
8 * 2 = 16
9 * 2 = 18
10 * 2 = 20


In [42]:
a=int(input());
b=int(input());
for i in range(a+1,b):
    print(i)

8
15
9
10
11
12
13
14


In [43]:
for i in range(2,11,2):
    print(i);
    

2
4
6
8
10


In [58]:
count=0;
for i in range(1,11):
    if(i%2!=0):
        print(i);
        count+=1;
print("count is",count);        

1
3
5
7
9
count is 5


In [57]:
ec=0
oc=0
for i in range(1,10+1):
    if(i%2==0):
        ec+=1;
    else:
        oc+=1;
print("odd count:",oc);
print("even count:",ec);
for i in range(1,10+1):
    if(i%2==0):
        print(i);
        

odd count: 5
even count: 5
2
4
6
8
10


In [64]:
c=0;
for i in range(1,100):
    if(i%3==0 and i%5==0):
        print(i);
        c+=1;
print("count:",c);        

15
30
45
60
75
90
count: 6


In [69]:
sum=0;
for i in range(1,6):
    sum+=i;
print(sum);

    

15


In [72]:
sum=0;
c=0;
for i in range(1,11):
        sum=sum+i;
        c+=1;
print(c);
print("sum:",sum);
print("avg:",sum/c);


10
sum: 55
avg: 5.5


In [79]:
for i in range(1,11):
    a=int(input(f"Enter the {i} number:"));

Enter the 1 number:1
Enter the 2 number:1
Enter the 3 number:1
Enter the 4 number:11
Enter the 5 number:1
Enter the 6 number:11
Enter the 7 number:1
Enter the 8 number:1
Enter the 9 number:1
Enter the 10 number:1


In [84]:
a=[];
for i in range(10):
    i=input("No.:");
    a.append(i);
print(a)

No.:9
No.:9
No.:9
No.:9
No.:99
No.:9
No.:9
No.:9
No.:9
No.:9
['9', '9', '9', '9', '99', '9', '9', '9', '9', '9']


In [ ]:
 a=[];
for i in range(1,10+1):
    i=input("No."+ str(i)+" num");
    a.append(i);
print(a)

In [1]:
for i in range(3):
    for j in range(1,3):
        print(j,"apple");

1 apple
2 apple
1 apple
2 apple
1 apple
2 apple


In [5]:
for i in range(1,3):
    print("--------");
    print("week:",i);   print("--------");
    for j in range(1,4):
        print("day:",j);
     

--------
week: 1
--------
day: 1
day: 2
day: 3
--------
week: 2
--------
day: 1
day: 2
day: 3


In [14]:
for i in range(4):
    print();
    for j in range(i+1):
        print("*",end="");


*
**
***
****

In [16]:
for i in range(1,5):
    print();
    for j in range(1,i+1):
        print(j,end="");
    


1
12
123
1234

In [17]:
i=0;
while(i==0):
    print(i);
    i=1;
    

0


In [18]:
i=1;
while(i<=5):
    print(i);
    i=i+1;

1
2
3
4
5


In [20]:
i=10;
while(i<=200):
    print(i,end=" ");
    i=i+10;

10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 

In [21]:
i=10;
while(i>=1):
    print(i);
    i=i-1;

10
9
8
7
6
5
4
3
2
1


In [25]:
i=int(input());
fact=1;
while(i>=1):
    fact=fact*i;
    i=i-1;
print(fact); 

0
1


In [62]:
##list
a=[1,2,3,4,5];
a.append(6)
print(a)

a.insert(1,44);
print("inserting:",a)

a[3]='updated';
print(a);

a.pop();
print("pop:",a)

a.pop(0);
print("after popping first element",a)

b=[1,2,3,4];
a.extend(b);
print(a);

a.append(b);
print(a);

a.extend([1,2,3]);
print(a);

a.remove(44);
print(a);

[1, 2, 3, 4, 5, 6]
inserting: [1, 44, 2, 3, 4, 5, 6]
[1, 44, 2, 'updated', 4, 5, 6]
pop: [1, 44, 2, 'updated', 4, 5]
after popping first element [44, 2, 'updated', 4, 5]
[44, 2, 'updated', 4, 5, 1, 2, 3, 4]
[44, 2, 'updated', 4, 5, 1, 2, 3, 4, [1, 2, 3, 4]]
[44, 2, 'updated', 4, 5, 1, 2, 3, 4, [1, 2, 3, 4], 1, 2, 3]
[2, 'updated', 4, 5, 1, 2, 3, 4, [1, 2, 3, 4], 1, 2, 3]


In [54]:
##tuple

a=(1,2,3);
b=list(a);
print(a);
b.pop();
print(b)

(1, 2, 3)
[1, 2]


In [89]:
a={9,4,2,0,5};
print(a);

a.add(3);
print("duplicate added after",a);

a.remove(3);
print("removing:",a);

a.add(4);
a.add('suba');
print(a);

a.pop();
print("after popping small number:",a);
 
b={10,11,12,13};
a.update(b);
print(a);


c={1,6,7,8};
a.update(c);
print(a);


{0, 2, 4, 5, 9}
duplicate added after {0, 2, 3, 4, 5, 9}
removing: {0, 2, 4, 5, 9}
{0, 2, 4, 5, 9, 'suba'}
after popping small number: {2, 4, 5, 9, 'suba'}
{2, 4, 5, 9, 10, 11, 12, 13, 'suba'}
{1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 'suba'}


In [111]:
a={
    "name":"suba",
    "class":"b",
    "dept":"aids",
    "rank":[1,2,3],
    "score":{90,80,70},
    "section":("a","b","c")
}
print(a);

print(a.keys());

print(a.values());
##update
a["name"]="jai";
print(a);

a.update({"class":"a"});
print(a);


##add new element
a["color"]="brown";
print(a);

a.pop("score");
print(a);

##delete
del a["rank"];
print(a);

del a
print("after delete",a);


{'name': 'suba', 'class': 'b', 'dept': 'aids', 'rank': [1, 2, 3], 'score': {80, 90, 70}, 'section': ('a', 'b', 'c')}
dict_keys(['name', 'class', 'dept', 'rank', 'score', 'section'])
dict_values(['suba', 'b', 'aids', [1, 2, 3], {80, 90, 70}, ('a', 'b', 'c')])
{'name': 'jai', 'class': 'b', 'dept': 'aids', 'rank': [1, 2, 3], 'score': {80, 90, 70}, 'section': ('a', 'b', 'c')}
{'name': 'jai', 'class': 'a', 'dept': 'aids', 'rank': [1, 2, 3], 'score': {80, 90, 70}, 'section': ('a', 'b', 'c')}
{'name': 'jai', 'class': 'a', 'dept': 'aids', 'rank': [1, 2, 3], 'score': {80, 90, 70}, 'section': ('a', 'b', 'c'), 'color': 'brown'}
{'name': 'jai', 'class': 'a', 'dept': 'aids', 'rank': [1, 2, 3], 'section': ('a', 'b', 'c'), 'color': 'brown'}
{'name': 'jai', 'class': 'a', 'dept': 'aids', 'section': ('a', 'b', 'c'), 'color': 'brown'}


NameError: name 'a' is not defined

In [128]:
a={
    "name":"suba",
    "class":"b",
    "dept":"aids",
    "rank":[1,2,3],
    "score":{90,80,70},
    "section":("a","b","c")
}
print(a);

b=a.get("name");
print("get fn",b);

##wrong way to use get
a.get("class");
print(a);

c=a.items();
print(list(c));

a.clear();
print(a);



{'name': 'suba', 'class': 'b', 'dept': 'aids', 'rank': [1, 2, 3], 'score': {80, 90, 70}, 'section': ('a', 'b', 'c')}
get fn suba
{'name': 'suba', 'class': 'b', 'dept': 'aids', 'rank': [1, 2, 3], 'score': {80, 90, 70}, 'section': ('a', 'b', 'c')}
[('name', 'suba'), ('class', 'b'), ('dept', 'aids'), ('rank', [1, 2, 3]), ('score', {80, 90, 70}), ('section', ('a', 'b', 'c'))]
{}


In [129]:
def painter():
    print("painting");
painter();


painting


In [134]:
def add(a,b):
    add=a+b;
    print(add);
a=input("Enter a:");
b=input("Enter b:");
add(a,b);  
    

Enter a:1
Enter b:2
12


In [136]:
def findevenorodd(a):
    if(a%2==0):
        print("even");
    else:
        print("odd");
a=int(input("enter a:"));
findevenorodd(a);
    

enter a:3
odd


In [3]:
def frange(a,b):
    for i in range(a,b):
        print(i);
a=int(input("Enter a:"));
b=int(input("Enter b:"));
frange(a,b);

Enter a:1
Enter b:11
1
2
3
4
5
6
7
8
9
10


In [7]:
a=[2,3,4,5,6,7]
for i in range(len(a)):
    for j in range(i+1,len(a)):
        if(a[i]+a[j]==9):
            print(a[i],a[j]);

2 7
3 6
4 5


In [2]:
a="Lavanya"
b="Ramesh"
for i in a:
    for j in b:
        if (i==j):
            print(i);

a
a
a


In [3]:
def painter():
    return "I am painter"
a=painter()
print(a)

I am painter


In [8]:
s_username="EMC"
s_password="123"
uname=input("Enter uname");
password=input("Enter password");

def validate():
    if(uname==s_username and password==s_password):
        return True
    else:
        return False
    
a=validate()
print(a)

Enter unameemc
Enter password123
False


In [ ]:
s_username="EMC"
s_password="123"
uname=input("Enter uname");
password=input("Enter password");

def validate():
    if(uname==s_username and password==s_password):
        print("True") 
    else:
        print("False")
    
validate()

In [12]:
a=int(input())
b=int(input())
c=int(input())
def add(a,b):
    return a+b
d=add(a,b)*c;
print(d)

1
2
3
9


In [16]:
class goa:
    drink=""
    def party(self):
        print("Let's party");
    def beach(self):
        print("Enjoying the beach");
        
ramesh=goa()
suresh=goa()
ramesh.party()

Let's party


In [20]:
for i in range(5):
    print()
    for j in range(5):
        print(j,end="")


01234
01234
01234
01234
01234

In [21]:
for i in range(5):
    print()
    for j in range(i+1):
        print(j,end="");


0
01
012
0123
01234

In [36]:
for i in range(5):
    print();
    for j in range(i,5):
        print(j,end="");
        


01234
1234
234
34
4

In [44]:
for i in range(5):
    print()
    for j in range(i,5):
        print(" ",end="");   
    for j in range(i+1):
        print("*",end='')
    


     *
    **
   ***
  ****
 *****

In [53]:
for i in range(5):
    print()
    for j in range(0,i):
        print(" ",end="")
    for j in range(i,5):
        print("*",end="")


*****
 ****
  ***
   **
    *

In [55]:
for i in range(5):
    print()
    for j in range(i,5):
        print(" ",end="")
    for j in range(i+1):
        print("*",end="")
    for j in range(i+1):
        print("*",end="")
        


     **
    ****
   ******
  ********
 **********

In [56]:
for i in range(5):
    print()
    for j in range(i,5):
        print(" ",end="")
    for j in range(i):
        print("*",end="")
    for j in range(i+1):
        print("*",end="")


     *
    ***
   *****
  *******
 *********

In [68]:
for i in range(5):
    print()
    for j in range(i+1):
        print(" ",end="")
    for j in range(i,5):
        print("*",end="")
    for j in range(i,5):
        print("*",end="")


 **********
  ********
   ******
    ****
     **

In [67]:
for i in range(5):
    print()
    for j in range(i+1):
        print(" ",end="")
    for j in range(i,5-1):
        print("*",end="")
    for j in range(i,5):
        print("*",end="")


 *********
  *******
   *****
    ***
     *

In [78]:
for i in range(5-1):
    print()
    for j in range(i,5):
        print(" ",end="")
    for j in range(i):
        print("*",end="")
    for j in range(i+1):
        print("*",end="")
for i in range(5):
    print()
    for k in range(i+1):
        print(" ",end="")
    for k in range(i,5-1):
        print("*",end="")
    for k in range(i,5):
        print("*",end="")


     *
    ***
   *****
  *******
 *********
  *******
   *****
    ***
     *

In [1]:
num =1 + int(1.0)
print(num)

2


In [2]:
print(type(num))

<class 'int'>


In [4]:
num=str(10)
print("the string is ",num)

the string is  10


In [5]:
radius=int(input())
area=3.14*radius*radius
print(area)

5
78.5


In [6]:
a=356
b=245
c=89
d=a+c-b
print(d)


200


In [7]:
print("Let's see some examples.\n\nDid you notice the empty lines?")
print("Do you notice\t the tab space?\nDid you see that I have moved to next line?")
print("Do you want a \" in your text?")
print("Are you going to store more info about escape sequence in Z:\\\\user\\escape_sequence.txt??")
#Every print starts with a new line, end can change that behavior by specifying your own character
print("Did you see I start here", end=" ")
print("and I end in the same line although from a different print?")
print("As observed escape sequences help you to format your output.")


Let's see some examples.

Did you notice the empty lines?
Do you notice	 the tab space?
Did you see that I have moved to next line?
Do you want a " in your text?
Are you going to store more info about escape sequence in Z:\\user\escape_sequence.txt??
Did you see I start here and I end in the same line although from a different print?
As observed escape sequences help you to format your output.


In [17]:
for i in range(10,0,-2):
    print(i)

10
8
6
4
2


In [18]:
for number in range(1,5):
    print ("The current number is ",number)

print("---------------------------")

for number in range(1,7,2):
    print ("The current number is ",number)

print("---------------------------")

for number in range(5,0,-1):
    print ("The current number is ",number)

The current number is  1
The current number is  2
The current number is  3
The current number is  4
---------------------------
The current number is  1
The current number is  3
The current number is  5
---------------------------
The current number is  5
The current number is  4
The current number is  3
The current number is  2
The current number is  1


In [6]:
number_of_passengers=5
number_of_baggage=2
security_check=True
for passenger_count in range(1, number_of_passengers+1):
    for baggage_count in range(1,number_of_baggage+1):
        if(security_check==True):
            print("Security check of passenger:", passenger_count, "-- baggage:", baggage_count,"baggage cleared")
        else:
            print("Security check of passenger:", passenger_count, "-- baggage:", baggage_count,"baggage not cleared")


Security check of passenger: 1 -- baggage: 1 baggage cleared
Security check of passenger: 1 -- baggage: 2 baggage cleared
Security check of passenger: 2 -- baggage: 1 baggage cleared
Security check of passenger: 2 -- baggage: 2 baggage cleared
Security check of passenger: 3 -- baggage: 1 baggage cleared
Security check of passenger: 3 -- baggage: 2 baggage cleared
Security check of passenger: 4 -- baggage: 1 baggage cleared
Security check of passenger: 4 -- baggage: 2 baggage cleared
Security check of passenger: 5 -- baggage: 1 baggage cleared
Security check of passenger: 5 -- baggage: 2 baggage cleared


In [8]:
i=1;
while(i<=10):
    print(i)
    i=i+1

1
2
3
4
5
6
7
8
9
10


In [12]:
for i in 1,2,3:
    print("i: ",i)

i:  1
i:  2
i:  3


In [16]:
for passenger in "A","A", "FC", "C", "FA", "SP", "A", "A":
    if(passenger=="FC" or passenger=="FA"):
        print("No check required")
        continue
    if(passenger=="SP"):
        print("Declare emergency in the airport")
        break
    if(passenger=="A" or passenger=="C"):
        print("Proceed with normal security check")
    print("Check the person")
    print("Check for cabin baggage")


Proceed with normal security check
Check the person
Check for cabin baggage
Proceed with normal security check
Check the person
Check for cabin baggage
No check required
Proceed with normal security check
Check the person
Check for cabin baggage
No check required
Declare emergency in the airport


In [21]:
for i in range(1,5,-1):
    print(i)

In [23]:
i=0
while(i<=9):
    if(i%2==0):
        pass
    else:
        print(i,end="")
    i+=1

13579

In [25]:
numbers_list = [98,45,60,71,90]
count = 10
for number in numbers_list:
    if number % 10 == 0:
        count -= 1
        continue
    counter = 0
    while counter < 2:
        last_digit = number % 10
        number = number // 10
        if last_digit > 4:
            count += 1
            break
        count += 1
        counter += 1
print(count)
 

12


In [30]:
def find_sum_of_digits(number):
    sum_of_digits=0
    #Write your logic here
    number1=number%10;
    number2=number//10
    number3=number//100
    sum_of_digits=number1 + number2 + number3
    return sum_of_digits

#Provide different values for number and test your program
sum_of_digits=find_sum_of_digits(123)
print("Sum of digits:",sum_of_digits)
                                          

Sum of digits: 16


In [35]:
x=123
n=x%100
print(n//10)

2


In [39]:
#PF-Assgn-15
def find_product(num1,num2,num3):
    #write your logic here
    product = num1*num2*num3
    return product
#Provide different values for num1, num2, num3 and test your program 
product=find_product(7,6,2)
print(product)


84


In [48]:
def n(x,y,z):
    product=0;
    if(x==7):
        product=y*z
    elif(y==7):
        product=z
    elif(x!=7 and y!=7 and z!=7):
        product=x*y*z
    else:
        product=-1
    return product
product=n(1,6,7)
print(product)

-1


In [55]:
def form_triangle(num1,num2,num3):
    success="Triangle can be formed"
    failure="Triangle can't be formed"
    if((num1>=(num2+num3))or(num2>=(num1+num3))or(num3>=(num1+num2))):
        return success
    else:
        return failure


num1=8
num2=3
num3=5
form_triangle(num1, num2, num3)

'Triangle can be formed'

In [61]:
def make_amount(amt,five,one):
    five_needed=0
    one_needed=0
    five_needed=min(five,amt//5)
    print(five_needed)
    one_needed=amt-five_needed*5
    print(one_needed)
    

#Provide different values for rupees_to_make,no_of_five,no_of_one and test your program
make_amount(28,10,5)

5
3
